### PR TITLE
OpenAPI v3 with drf-spectacular

### PR DESCRIPTION
**Pull request by mdellweg**
Required PR: https://github.com/pulp/pulpcore/pull/785
[noissue]

### CODE REVIEW

**Comment by mdellweg** [comment]
Is the open-pr mechanism not working here?

**Comment by fao89** [comment]
I don't know exactly what is happening, bug the problem is here:
https://github.com/pulp/pulp_npm/blob/master/.github/install.sh#L47-L85
it is not getting into the right pulpcore, for some reason the the "if" is not doing its job

**Comment by dkliban** [comment]
We probably need to update the travis config using plugin-template.

**Comment by mdellweg** [comment]
This is not using travis...

**Comment by mdellweg** [comment]
@fao89 starting from line https://github.com/pulp/pulp_npm/blob/9f0994e355c06dc0a039653d8590b07195cb0529/.github/install.sh#L32 all the ifs regarding `$GITHUB_REF` seem a bit unfinished.

**Comment by mdellweg** [comment]
@fao89 is there a plugin template for this CI, yet? Also ready for final review!

**Comment by fao89** [comment]
> @fao89 is there a plugin template for this CI, yet? Also ready for final review!

No, I've been doing it manually (applying plugin_template and s/travis/github)

**Pull request merged**
